package game

UPGRADE_DEFS: [Upgrade_Id]Upgrade_Def = {
	.None = {},
	.Gravity_Tuning = {
		name = "Gravity Tuning",
		desc = "Increases universal gravitational constant.",
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, -1},
	},
	.Orbital_Yield = {
		name = "Orbital Yield",
		desc = "Increases energy generated from orbiting bodies.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, 1},
	},
	.Collector_Reach = {
		name = "Collector Reach",
		desc = "Expands the reach of cursor collector interaction.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {},
		requires = {},
		pos = {0, 3},
	},
	.Moonlet_Foundry = {
		name = "Moonlet Foundry",
		desc = "Unlocks Moonlet celestials in the slingshot menu.",
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Grant{celestial = .Moonlet},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -6},
	},
	.Launch_Efficiency = {
		name = "Launch Efficiency",
		desc = "Reduces energy cost of launching celestials.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -2},
	},
	.Slingshot_Foresight = {
		name = "Slingshot Foresight",
		desc = "Extends slingshot orbit trajectory preview duration.",
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -4},
	},
	.Star_Furnace = {
		name = "Star Furnace",
		desc = "Boosts energy output from energy sources.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Orbital_Yield, .None, .None, .None},
		pos = {2, 0},
	},
	.Salvage_Rights = {
		name = "Salvage Rights",
		desc = "Increases energy refund when objects leave or decay.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {kind = .Lifetime_Energy_Earned},
		requires = {.Orbital_Yield, .None, .None, .None},
		pos = {2, 2},
	},
	.Emitter_Logistics = {
		name = "Emitter Logistics",
		desc = "Reduces the cost of emitter presets.",
		category = .Automation,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {kind = .Celestial_Discovered, celestial = .DwarfPlanet},
		requires = {.Launch_Efficiency, .Star_Furnace, .None, .None},
		pos = {4, -1},
	},
	.Emitter_Persistence = {
		name = "Emitter Persistence",
		desc = "Increases duration of active emitter stations.",
		category = .Automation,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Emitter_Logistics, .None, .None, .None},
		pos = {6, -1},
	},
	.Research_Grants = {
		name = "Research Grants",
		desc = "Reduces base cost of all other upgrade nodes.",
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {kind = .Upgrades_Purchased},
		requires = {.Salvage_Rights, .Star_Furnace, .None, .None},
		pos = {4, 2},
	},
	.Tractor_Field = {
		name = "Tractor Field",
		desc = "Attracts floating energy fragments toward your cursor.",
		category = .Hardware,
		scope = .Run,
		effect = Upgrade_Effect_Capability{capability = .Fragment_Attraction},
		condition = {kind = .Lifetime_Energy_Earned},
		requires = {.Collector_Reach, .Salvage_Rights, .None, .None},
		pos = {4, 4},
	},
	.Stellar_Legacy = {
		name = "Stellar Legacy",
		desc = "Meta progression placeholder.",
		category = .Economy,
		scope = .Meta,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, 8},
	},
}
