package game

UPGRADE_DEFS: [Upgrade_Id]Upgrade_Def = {
	.None = {},
	.Gravity_Tuning = {
		name_msg = .Upgrade_GravityTuning_Name,
		desc_msg = .Upgrade_GravityTuning_Desc,
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, -1},
	},
	.Orbital_Yield = {
		name_msg = .Upgrade_OrbitalYield_Name,
		desc_msg = .Upgrade_OrbitalYield_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, 1},
	},
	.Collector_Reach = {
		name_msg = .Upgrade_CollectorReach_Name,
		desc_msg = .Upgrade_CollectorReach_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {},
		requires = {},
		pos = {0, 3},
	},
	.Moonlet_Foundry = {
		name_msg = .Upgrade_MoonletFoundry_Name,
		desc_msg = .Upgrade_MoonletFoundry_Desc,
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Grant{celestial = .Moonlet},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -6},
	},
	.Launch_Efficiency = {
		name_msg = .Upgrade_LaunchEfficiency_Name,
		desc_msg = .Upgrade_LaunchEfficiency_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -2},
	},
	.Slingshot_Foresight = {
		name_msg = .Upgrade_SlingshotForesight_Name,
		desc_msg = .Upgrade_SlingshotForesight_Desc,
		category = .Physics,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {},
		requires = {.Gravity_Tuning, .None, .None, .None},
		pos = {2, -4},
	},
	.Star_Furnace = {
		name_msg = .Upgrade_StarFurnace_Name,
		desc_msg = .Upgrade_StarFurnace_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Orbital_Yield, .None, .None, .None},
		pos = {2, 0},
	},
	.Salvage_Rights = {
		name_msg = .Upgrade_SalvageRights_Name,
		desc_msg = .Upgrade_SalvageRights_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Add},
		condition = {kind = .Lifetime_Energy_Earned},
		requires = {.Orbital_Yield, .None, .None, .None},
		pos = {2, 2},
	},
	.Emitter_Logistics = {
		name_msg = .Upgrade_EmitterLogistics_Name,
		desc_msg = .Upgrade_EmitterLogistics_Desc,
		category = .Automation,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {kind = .Celestial_Discovered, celestial = .DwarfPlanet},
		requires = {.Launch_Efficiency, .Star_Furnace, .None, .None},
		pos = {4, -1},
	},
	.Emitter_Persistence = {
		name_msg = .Upgrade_EmitterPersistence_Name,
		desc_msg = .Upgrade_EmitterPersistence_Desc,
		category = .Automation,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {.Emitter_Logistics, .None, .None, .None},
		pos = {6, -1},
	},
	.Research_Grants = {
		name_msg = .Upgrade_ResearchGrants_Name,
		desc_msg = .Upgrade_ResearchGrants_Desc,
		category = .Economy,
		scope = .Run,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {kind = .Upgrades_Purchased},
		requires = {.Salvage_Rights, .Star_Furnace, .None, .None},
		pos = {4, 2},
	},
	.Tractor_Field = {
		name_msg = .Upgrade_TractorField_Name,
		desc_msg = .Upgrade_TractorField_Desc,
		category = .Hardware,
		scope = .Run,
		effect = Upgrade_Effect_Capability{capability = .Fragment_Attraction},
		condition = {kind = .Lifetime_Energy_Earned},
		requires = {.Collector_Reach, .Salvage_Rights, .None, .None},
		pos = {4, 4},
	},
	.Stellar_Legacy = {
		name_msg = .Upgrade_StellarLegacy_Name,
		desc_msg = .Upgrade_StellarLegacy_Desc,
		category = .Economy,
		scope = .Meta,
		effect = Upgrade_Effect_Param{op = .Mul},
		condition = {},
		requires = {},
		pos = {0, 8},
	},
}
