#+TITLE: Balancing the game

#+NAME: constants
| Name                   | Value |
|------------------------+-------|
| G                      |     1 |
| StarBaseOutput         |     1 |
| SlingshotPower         |     1 |
| EnergyGainFactor       |     1 |
| EnergySourceGainFactor |    10 |
|                        |       |

* Phase 1 - Introduction
In phase 1, the player is launching simple objects, triggering collisions and
merges. The primary objective here is to merge as many objects as possible and
unlock larger celestials. The player should not spend more than 5 mins in this
phase.

When the game starts, the player gets a steaady source of energy from the
central star. The central star should emit enough energy to launch a celestial
at a good initial pace every 5-7 seconds. The initial pace of the celestial
should be such that the celestial itself generates enough energy to launch
another one every 15-30 seconds. This would lead to a solid loop of around.

#+NAME: StarOutput
| Density | Radius | Time | Output |
|---------+--------+------+--------|
|      50 |     40 |    1 |   2000 |
|     100 |     40 |    1 |   4000 |
|    1000 |     40 |    1 |  40000 |
#+TBLFM: $4=$3*$2*$1
